"""Curated route catalog for optional dependency installation."""

from __future__ import annotations

from importlib.util import find_spec

from nwbforge.app.packages.models import InstallPreset, RoutePackageSpec


ROUTE_PACKAGE_CATALOG: tuple[RoutePackageSpec, ...] = (
    RoutePackageSpec(
        route_name="audio",
        display_name="Audio",
        extra_name="audio",
        description="AudioInterface plus required sound/array dependencies.",
        required_modules=("ndx_sound", "scipy"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="alphaomega",
        display_name="AlphaOmega",
        extra_name="alphaomega",
        description="AlphaOmega ecephys support through NeuroConv's alphaomega extra.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="axon",
        display_name="Axon / ABF",
        extra_name="axon",
        description="Axon Binary Format support through SpikeInterface-backed NeuroConv readers.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="axona",
        display_name="Axona",
        extra_name="axona",
        description="Axona recording support through NeuroConv's axona extra.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="biocam",
        display_name="Biocam",
        extra_name="biocam",
        description="Biocam MEA recording support through NeuroConv's biocam extra.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="blackrock",
        display_name="Blackrock",
        extra_name="blackrock",
        description="Blackrock recording and sorting support through NeuroConv's blackrock extra.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="cellexplorer",
        display_name="Cell Explorer",
        extra_name="cellexplorer",
        description="Cell Explorer sorting support through NeuroConv's cellexplorer extra.",
        required_modules=("spikeinterface", "pymatreader"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="brukertiff",
        display_name="Bruker TIFF",
        extra_name="brukertiff",
        description="Bruker TIFF imaging support through NeuroConv's brukertiff extra.",
        required_modules=("roiextractors", "tifffile", "natsort"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="caiman",
        display_name="Caiman",
        extra_name="caiman",
        description="Caiman segmentation support through NeuroConv's caiman extra.",
        required_modules=("roiextractors", "scipy"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="deeplabcut",
        display_name="DeepLabCut",
        extra_name="deeplabcut",
        description="DeepLabCut pose-estimation support and the ndx-pose extension.",
        required_modules=("ndx_pose",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="cnmfe",
        display_name="CNMFE",
        extra_name="cnmfe",
        description="CNMFE segmentation support through NeuroConv's cnmfe extra.",
        required_modules=("roiextractors", "scipy"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="medpc",
        display_name="MedPC",
        extra_name="medpc",
        description="MedPC task/event support through NeuroConv's medpc extra and ndx-events.",
        required_modules=("ndx_events",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="lightningpose",
        display_name="LightningPose",
        extra_name="lightningpose",
        description="LightningPose pose-estimation support with required video and ndx-pose dependencies.",
        required_modules=("cv2", "ndx_pose"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="excel",
        display_name="Excel",
        extra_name="excel",
        description="Excel time-interval support through openpyxl-backed readers.",
        required_modules=("openpyxl",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="edf",
        display_name="EDF",
        extra_name="edf",
        description="European Data Format support through SpikeInterface-backed NeuroConv readers.",
        required_modules=("spikeinterface", "pyedflib"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="femtonics",
        display_name="Femtonics",
        extra_name="femtonics",
        description="Femtonics MESc imaging support through NeuroConv's femtonics extra.",
        required_modules=("roiextractors", "h5py"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="extract",
        display_name="EXTRACT",
        extra_name="extract",
        description="EXTRACT segmentation support through NeuroConv's extract extra.",
        required_modules=("roiextractors",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="image",
        display_name="Image",
        extra_name="image",
        description="Still-image support through Pillow-backed readers.",
        required_modules=("PIL",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="videos",
        display_name="Videos",
        extra_name="videos",
        description="External video support through NeuroConv's video interfaces and OpenCV-backed metadata readers.",
        required_modules=("cv2",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="viewer_rich",
        display_name="NWB Viewer Rich Preview",
        extra_name="viewer_rich",
        description="Optional `nwbwidgets + Panel` support for browser-backed rich preview from the integrated NWB viewer.",
        required_modules=("nwbwidgets", "panel", "ipython_genutils", "ipykernel", "ipywidgets_bokeh"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="sleap",
        display_name="SLEAP",
        extra_name="sleap",
        description="SLEAP pose-estimation support through NeuroConv's sleap extra and ndx-pose.",
        required_modules=("sleap_io", "ndx_pose"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="hdf5",
        display_name="HDF5 Imaging",
        extra_name="hdf5",
        description="Extractor-backed HDF5 imaging support through NeuroConv and roiextractors.",
        required_modules=("h5py", "roiextractors"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="micromanager",
        display_name="Micro-Manager TIFF",
        extra_name="micromanager",
        description="Micro-Manager TIFF imaging support through NeuroConv's micromanagertiff extra.",
        required_modules=("roiextractors", "tifffile"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="miniscope",
        display_name="Miniscope",
        extra_name="miniscope",
        description="Miniscope imaging support through NeuroConv's miniscope extra and ndx-miniscope.",
        required_modules=("roiextractors", "ndx_miniscope"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="mcsraw",
        display_name="MCSRaw",
        extra_name="mcsraw",
        description="MCSRaw MEA recording support through NeuroConv's mcsraw extra.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="maxone",
        display_name="MaxOne",
        extra_name="maxone",
        description="MaxOne recording support through NeuroConv's maxwell-backed reader stack.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="mearec",
        display_name="MEArec",
        extra_name="mearec",
        description="MEArec simulated recording support through NeuroConv's mearec extra.",
        required_modules=("MEArec",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="neuroscope",
        display_name="NeuroScope",
        extra_name="neuroscope",
        description="NeuroScope recording and sorting support through NeuroConv's neuroscope extra.",
        required_modules=("spikeinterface", "lxml"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="scanimage",
        display_name="ScanImage",
        extra_name="scanimage",
        description="ScanImage imaging support through NeuroConv's scanimage extra.",
        required_modules=("roiextractors", "tifffile"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="scanimage_legacy",
        display_name="ScanImage Legacy",
        extra_name="scanimage_legacy",
        description="ScanImage legacy TIFF support through NeuroConv's scanimage_legacy extra.",
        required_modules=("roiextractors", "tifffile"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="scanbox",
        display_name="Scanbox",
        extra_name="scanbox",
        description="Scanbox `.sbx` imaging support through NeuroConv's ophys-backed scanbox reader.",
        required_modules=("roiextractors",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="suite2p",
        display_name="Suite2p",
        extra_name="suite2p",
        description="Suite2p segmentation support through NeuroConv's suite2p extra.",
        required_modules=("roiextractors", "natsort"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="thor",
        display_name="Thor",
        extra_name="thor",
        description="ThorImageLS TIFF imaging support through NeuroConv's thor extra.",
        required_modules=("roiextractors", "tifffile"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="intan",
        display_name="Intan",
        extra_name="intan",
        description="Intan ecephys support through NeuroConv's intan extra and SpikeInterface.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="kilosort",
        display_name="KiloSort",
        extra_name="kilosort",
        description="KiloSort sorting support through NeuroConv's kilosort extra.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="inscopix",
        display_name="Inscopix",
        extra_name="inscopix",
        description="Inscopix imaging and segmentation support through NeuroConv's inscopix extra and the isx reader stack.",
        required_modules=("roiextractors", "isx"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="neuralynx",
        display_name="Neuralynx",
        extra_name="neuralynx",
        description="Neuralynx recording and sorting support through NeuroConv's neuralynx extra.",
        required_modules=("spikeinterface", "natsort"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="openephys_binary",
        display_name="OpenEphys Binary",
        extra_name="openephys_binary",
        description="OpenEphys binary support through SpikeInterface-backed NeuroConv readers.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="openephys_legacy",
        display_name="OpenEphys Legacy",
        extra_name="openephys_legacy",
        description="Legacy OpenEphys `.continuous` support through NeuroConv's openephys extra.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="plexon",
        display_name="Plexon",
        extra_name="plexon",
        description="Plexon `.plx` recording and sorting support through NeuroConv's plexon extra.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="plexon2",
        display_name="Plexon2",
        extra_name="plexon2",
        description="Plexon2 `.pl2` recording support through NeuroConv's plexon2 extra.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="phy",
        display_name="Phy",
        extra_name="phy",
        description="Phy sorting support through NeuroConv's phy extra.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="spike2",
        display_name="Spike2",
        extra_name="spike2",
        description="Spike2 `.smr/.smrx` support through NeuroConv's spike2 extra and the sonpy stack.",
        required_modules=("sonpy",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="spikegadgets",
        display_name="SpikeGadgets",
        extra_name="spikegadgets",
        description="SpikeGadgets `.rec` support through SpikeInterface-backed NeuroConv readers.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="spikeglx",
        display_name="SpikeGLX",
        extra_name="spikeglx",
        description="SpikeGLX imec stream support through SpikeInterface-backed NeuroConv readers.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="tiff",
        display_name="TIFF Imaging",
        extra_name="tiff",
        description="Generic TIFF imaging support through NeuroConv's TIFF interface plus roiextractors.",
        required_modules=("roiextractors", "tifffile"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="tdt",
        display_name="TDT",
        extra_name="tdt",
        description="TDT recording support through NeuroConv's tdt extra.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="tdt_fiber_photometry",
        display_name="TDT Fiber Photometry",
        extra_name="tdt_fiber_photometry",
        description="TDT fiber photometry support through NeuroConv's tdt-fp extra and the ndx-fiber-photometry extensions.",
        required_modules=("tdt", "ndx_fiber_photometry", "ndx_ophys_devices"),
        implemented_in_code=True,
    ),
    RoutePackageSpec(
        route_name="whitematter",
        display_name="WhiteMatter",
        extra_name="whitematter",
        description="WhiteMatter binary recording support through NeuroConv's whitematter extra.",
        required_modules=("spikeinterface",),
        implemented_in_code=True,
    ),
)

ROUTE_PACKAGE_BY_NAME = {spec.route_name: spec for spec in ROUTE_PACKAGE_CATALOG}

PRESET_ROUTE_NAMES: dict[InstallPreset, tuple[str, ...]] = {
    InstallPreset.MINIMAL: (),
    InstallPreset.COMMON: ("audio", "deeplabcut", "excel", "image"),
    InstallPreset.FULL: tuple(spec.route_name for spec in ROUTE_PACKAGE_CATALOG),
    InstallPreset.CUSTOM: (),
}


def route_dependencies_available(route_name: str) -> bool:
    """Return whether the current environment satisfies the curated dependency gate for a route."""

    spec = ROUTE_PACKAGE_BY_NAME[route_name]
    return all(find_spec(module_name) is not None for module_name in spec.required_modules)
